version: "3.7"

services:
  zookeeper-server:
    image: gudari/zookeeper:3.6.1
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
    - zookeeper.env

  hoster:
    image: dvdarias/docker-hoster
    container_name: zookeeper_hoster
    hostname: zookeeper_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
