trigger:
  branches:
    include:
    - master
  paths:
    include:
    - spark/build/*
    - spark/scripts/*
    - spark/Makefile
    - spark/Dockerfile.template.erb

pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/spark
    make release-all
