version: "3.7"

services:
  zookeeper-server:
    image: gudari/zookeeper:3.4.14
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
    - zookeeper.env
  zookeeper-rest:
    image: gudari/zookeeper-rest:3.4.14
    container_name: zookeeper-rest
    hostname: zookeeper-rest
    ports:
    - "9998:9998"
    env_file:
    - zookeeper-rest.env
