version: "3.7"

services:
  activemq-server:
    image: gudari/activemq:5.15.12
    container_name: activemq-server
    hostname: activemq-server
    networks:
      - docker.local

  hoster:
    image: dvdarias/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
