FROM <%= build_image %> AS BUILD

ARG OOZIE_VERSION=<%= version %>
ENV OOZIE_HOME /opt/oozie
ENV HADOOP_VERSION <%= hadoop_version %>

RUN apt-get update \
    && apt-get install --no-install-recommends -y wget \
    && wget https://archive.apache.org/dist/oozie/${OOZIE_VERSION}/oozie-${OOZIE_VERSION}.tar.gz \
    && mkdir -p ${OOZIE_HOME} \
    && tar -xzvf oozie-${OOZIE_VERSION}.tar.gz -C ${OOZIE_HOME} --strip-components=1 \
    && rm -rf oozie-${OOZIE_VERSION}.tar.gz \
    && cd ${OOZIE_HOME} \
    && bin/mkdistro.sh -Puber -Pspark-2 -DskipTests -Dhadoop.version=${HADOOP_VERSION}

FROM <%= base_image %>

LABEL maintainer "Axier Artola <aartola1986@gmail.com>"
LABEL Description="Apache Oozie docker image" Version="<%= version %>"

ARG OOZIE_VERSION=<%= version %>
ENV OOZIE_HOME /opt/oozie

COPY --from=BUILD ${OOZIE_HOME}/distro/target/oozie-${OOZIE_VERSION}-distro.tar.gz /oozie-${OOZIE_VERSION}-distro.tar.gz

RUN apt-get update \
    && apt-get install --no-install-recommends -y wget unzip \
    && mkdir -p ${OOZIE_HOME} \
    && tar -xzvf /oozie-${OOZIE_VERSION}-distro.tar.gz -C ${OOZIE_HOME} --strip-components=1 \
    && rm -rf oozie-${OOZIE_VERSION}-distro.tar.gz \
    && mkdir ${OOZIE_HOME}/libext \
    && wget http://archive.cloudera.com/gplextras/misc/ext-2.2.zip -O ${OOZIE_HOME}/libext/ext-2.2.zip \
    && apt-get remove -y wget \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p ${INIT_DIR}

WORKDIR $OOZIE_HOME

COPY scripts/bootstrap.sh ${INIT_DIR}/bootstrap.sh
RUN chmod +x ${INIT_DIR}/bootstrap.sh

CMD ${INIT_DIR}/bootstrap.sh
