trigger:
  branches:
    include:
    - master
  paths:
    include:
    - java/Makefile
    - java/Dockerfile.template.erb

pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/java
    make release-all
