version: "3.7"

services:
  zookeeper-server:
    image: gudari/zookeeper:3.4.14
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
    - zookeeper.env

  zkui:
    image: gudari/zkui:2.0-SNAPSHOT
    container_name: zkui
    hostname: zkui
    env_file:
    - zkui.env

  hoster:
    image: dvdarias/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
