trigger: none
#  branches:
#    include:
#    - master
#  paths:
#    include:
#    - hadoop/Makefile
#    - hadoop/scripts/*
#    - hadoop/build/*

pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/hadoop
    make release-all
