FROM <%= base_image %>

LABEL maintainer "Axier Artola <aartola1986@gmail.com>"
LABEL Description="Hadoop docker image" Version="<%= version %>"

ARG HADOOP_VERSION=<%= version %>
ENV HADOOP_HOME=/opt/hadoop
ENV INIT_DIR=/opt/init

RUN apt-get update \
    && apt-get install --no-install-recommends -y wget netcat \
    && wget https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz \
    && mkdir -p $HADOOP_HOME \
    && tar -xvzf hadoop-${HADOOP_VERSION}.tar.gz -C ${HADOOP_HOME} --strip-components=1 \
    && rm -fr hadoop-${HADOOP_VERSION}.tar.gz \
    ## Remove not required files and folders
    && rm -fr $HADOOP_HOME/share/doc \
    && find $HADOOP_HOME/share/hadoop/ -type d -name sources -prune -exec rm -rf {} \; \
    && find $HADOOP_HOME/share/hadoop/ -type d -name jdiff -prune -exec rm -rf {} \; \
    && find $HADOOP_HOME/share/hadoop/ -type d -name templates -prune -exec rm -rf {} \; \
    && find $HADOOP_HOME/share/hadoop/ -type f -name *tests* -exec rm -fr {} \; \
    && apt-get remove -y wget \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p ${INIT_DIR}

ENV HADOOP_PREFIX=${HADOOP_HOME} \
    HADOOP_COMMON_HOME=${HADOOP_HOME} \
    HADOOP_HDFS_HOME=${HADOOP_HOME} \
    HADOOP_MAPRED_HOME=${HADOOP_HOME} \
    HADOOP_YARN_HOME=${HADOOP_HOME} \
    HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop \
    YARN_CONF_DIR=${HADOOP_HOME}/etc/hadoop \
    PATH=${PATH}:${HADOOP_HOME}/bin

WORKDIR $HADOOP_PREFIX

COPY scripts/bootstrap.sh ${INIT_DIR}/bootstrap.sh
RUN chmod +x ${INIT_DIR}/bootstrap.sh

CMD ${INIT_DIR}/bootstrap.sh
