trigger:
  branches:
    include:
    - master
  paths:
    include:
    - build/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: |
    cd $(Build.SourcesDirectory)/kafka-manager/build
    ./build.sh
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/kafka-manager/build
    ./push.sh

