trigger:
  branches:
    include:
    - master
  paths:
    include:
    - hive/Makefile
    - hive/scripts/*
    - hive/build/*

pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/hive
    make release-all
