trigger: none
#  branches:
#    include:
#    - master
#  paths:
#    include:
#    - hbase/Makefile
#    - hbase/scripts/*
#    - hbase/build/*

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/hbase
    make release-all

