version: "3.7"

services:



  zookeeper-server-0:
    image: gudari/zookeeper:3.4.14
    container_name: zookeeper-server-0
    hostname: zookeeper-server-0
    environment:
      ZOO_CFG_server_0: "zookeeper-server-0:2888:3888"
      ZOO_CFG_server_1: "zookeeper-server-1:2888:3888"
      ZOO_CFG_server_2: "zookeeper-server-2:2888:3888"
      ZOO_MYID: 0
    env_file:
    - zookeeper.env
    networks:
      - hadoop.local

  zookeeper-server-1:
    image: gudari/zookeeper:3.4.14
    container_name: zookeeper-server-1
    hostname: zookeeper-server-1
    environment:
      ZOO_CFG_server_0: "zookeeper-server-0:2888:3888"
      ZOO_CFG_server_1: "zookeeper-server-1:2888:3888"
      ZOO_CFG_server_2: "zookeeper-server-2:2888:3888"
      ZOO_MYID: 1
    env_file:
    - zookeeper.env
    networks:
      - hadoop.local

  zookeeper-server-2:
    image: gudari/zookeeper:3.4.14
    container_name: zookeeper-server-2
    hostname: zookeeper-server-2
    environment:
      ZOO_CFG_server_0: "zookeeper-server-0:2888:3888"
      ZOO_CFG_server_1: "zookeeper-server-1:2888:3888"
      ZOO_CFG_server_2: "zookeeper-server-2:2888:3888"
      ZOO_MYID: 2
    env_file:
    - zookeeper.env
    networks:
      - hadoop.local




  journalnode-0:
    image: gudari/hadoop:3.1.3
    container_name: journalnode-0
    hostname: journalnode-0
    volumes:
      - ./storage/journalnode_0:/hadoop/dfs/journal
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  journalnode-1:
    image: gudari/hadoop:3.1.3
    container_name: journalnode-1
    hostname: journalnode-1
    volumes:
      - ./storage/journalnode_1:/hadoop/dfs/journal
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  journalnode-2:
    image: gudari/hadoop:3.1.3
    container_name: journalnode-2
    hostname: journalnode-2
    volumes:
      - ./storage/journalnode_2:/hadoop/dfs/journal
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local




  namenode-0:
    image: gudari/hadoop:3.1.3
    container_name: namenode-0
    hostname: namenode-0
    environment:
      SERVICE_PRECONDITION: "journalnode-0:8480 journalnode-1:8480 journalnode-2:8480 zookeeper-server-0:2181 zookeeper-server-1:2181 zookeeper-server-2:2181"
    volumes:
      - ./storage/namenode_0:/hadoop/dfs/name
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  namenode-1:
    image: gudari/hadoop:3.1.3
    container_name: namenode-1
    hostname: namenode-1
    environment:
      SERVICE_PRECONDITION: "journalnode-0:8480 journalnode-1:8480 journalnode-2:8480 zookeeper-server-0:2181 zookeeper-server-1:2181 zookeeper-server-2:2181"
    volumes:
      - ./storage/namenode_1:/hadoop/dfs/name
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local




  datanode-0:
    image: gudari/hadoop:3.1.3
    container_name: datanode-0
    hostname: datanode-0
    volumes:
      - ./storage/datanode_0:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070"
    depends_on:
      - namenode-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  datanode-1:
    image: gudari/hadoop:3.1.3
    container_name: datanode-1
    hostname: datanode-1
    volumes:
      - ./storage/datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070"
    depends_on:
      - namenode-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local




  resourcemanager-0:
    image: gudari/hadoop:3.1.3
    container_name: resourcemanager-0
    hostname: resourcemanager-0
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075"
    depends_on:
      - namenode-0
      - datanode-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  resourcemanager-1:
    image: gudari/hadoop:3.1.3
    container_name: resourcemanager-1
    hostname: resourcemanager-1
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075"
    depends_on:
      - namenode-0
      - datanode-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local




  nodemanager-0:
    image: gudari/hadoop:3.1.3
    container_name: nodemanager-0
    hostname: nodemanager-0
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075 resourcemanager-0:8088"
    depends_on:
      - namenode-0
      - datanode-0
      - resourcemanager-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  nodemanager-1:
    image: gudari/hadoop:3.1.3
    container_name: nodemanager-1
    hostname: nodemanager-1
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075 resourcemanager-0:8088"
    depends_on:
      - namenode-0
      - datanode-0
      - resourcemanager-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local


  historyserver:
    image: gudari/hadoop:3.1.3
    container_name: historyserver
    hostname: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075 resourcemanager-0:8088"
    depends_on:
      - namenode-0
      - datanode-0
      - resourcemanager-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  timelineserver:
    image: gudari/hadoop:3.1.3
    container_name: timelineserver
    hostname: timelineserver
    environment:
      SERVICE_PRECONDITION: "namenode-0:50070 datanode-0:50075 resourcemanager-0:8088"
    depends_on:
      - namenode-0
      - datanode-0
      - resourcemanager-0
    env_file:
      - ./hadoop-ha.env
    networks:
      - hadoop.local

  hoster:
    image: dvdarias/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
    networks:
      - hadoop.local

networks:
  hadoop.local:
    driver: bridge
    name: hadoop.local
