trigger:
  branches:
    include:
    - nifi-toolkit-server
  paths:
    include:
    - nifi-ca-server/build/*

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: |
    cd $(Build.SourcesDirectory)/nifi-ca-server/build
    ./build.sh
- bash: |
    export DOCKER_PASSWORD=$(docker_password)
    export DOCKER_USERNAME=$(docker_username)
    cd $(Build.SourcesDirectory)/nifi-ca-server/build
    ./push.sh

